"""customer portal: client_id, action items, artifacts

Revision ID: 2c97e3dcbb33
Revises: 477c94a3f62d
Create Date: 2026-06-13 09:40:46.918509
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2c97e3dcbb33'
down_revision: str | None = '477c94a3f62d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_client_id_clients'), 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_client_id_clients'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###
