"""quote_line unit_cost

Revision ID: 72625f2a7865
Revises: a285cd23d2a3
Create Date: 2026-06-12 19:36:52.771699
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '72625f2a7865'
down_revision: str | None = 'a285cd23d2a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_lines', sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_lines', 'unit_cost')
    # ### end Alembic commands ###
