"""customer action items and artifacts

Revision ID: 54c7b40490b7
Revises: 2c97e3dcbb33
Create Date: 2026-06-13 09:42:36.607670
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '54c7b40490b7'
down_revision: str | None = '2c97e3dcbb33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_action_items',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsible_name', sa.String(length=255), nullable=False),
    sa.Column('responsible_email', sa.String(length=255), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('provided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provided_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_customer_action_items_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_customer_action_items_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], name=op.f('fk_customer_action_items_responsible_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_action_items'))
    )
    op.create_index(op.f('ix_customer_action_items_project_id'), 'customer_action_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_customer_action_items_status'), 'customer_action_items', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('action_item_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_item_id'], ['customer_action_items.id'], name=op.f('fk_artifacts_action_item_id_customer_action_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_artifacts_project_id_projects')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_artifacts_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_action_item_id'), 'artifacts', ['action_item_id'], unique=False)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_action_item_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_customer_action_items_status'), table_name='customer_action_items')
    op.drop_index(op.f('ix_customer_action_items_project_id'), table_name='customer_action_items')
    op.drop_table('customer_action_items')
    # ### end Alembic commands ###
